model_params:
  _target_: models.vae.VQVAE
  name: 'VQVAE'
  in_channels: 3
  latent_dim: 256
  embedding_dim: 128
  num_embeddings: 512
  img_size: 64
  beta: 0.25


data_params:
  _target_: datasets.ImagenetteDataset
  name: 'imagenette'
  data_path: "/mnt/data/alzaig"
  img_size: 256
  batch_size: 64
  workers: 8


exp_params:
  seed: 0
  criterion_name: smoothl1
  criterion_delta: 0.5
  device: cuda
  epochs: 100
  log_images_interval: 10
  checkpoint_freq: 10


optimizer:
  _target_: torch.optim.SGD
  momentum: 0.9
  weight_decay: 0.0
  lr: 0.005


logging_params:
  log_dir: "/mnt/data/alzaig/logs"
  checkpoint_dir: "/mnt/data/alzaig/checkpoints"
